"""Add OEE and WorkOrder

Revision ID: 30c9d07e83e2
Revises: 85a71ab74cdc
Create Date: 2026-06-28 09:03:34.384404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c9d07e83e2'
down_revision: Union[str, Sequence[str], None] = '85a71ab74cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oeerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('oee_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oeerecord_id'), 'oeerecord', ['id'], unique=False)
    op.create_index(op.f('ix_oeerecord_machine_id'), 'oeerecord', ['machine_id'], unique=False)
    op.create_index(op.f('ix_oeerecord_time'), 'oeerecord', ['time'], unique=False)
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workorder_id'), 'workorder', ['id'], unique=False)
    op.create_index(op.f('ix_workorder_machine_id'), 'workorder', ['machine_id'], unique=False)
    op.drop_index(op.f('telemetry_time_idx'), table_name='telemetry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('telemetry_time_idx'), 'telemetry', [sa.literal_column('time DESC')], unique=False)
    op.drop_index(op.f('ix_workorder_machine_id'), table_name='workorder')
    op.drop_index(op.f('ix_workorder_id'), table_name='workorder')
    op.drop_table('workorder')
    op.drop_index(op.f('ix_oeerecord_time'), table_name='oeerecord')
    op.drop_index(op.f('ix_oeerecord_machine_id'), table_name='oeerecord')
    op.drop_index(op.f('ix_oeerecord_id'), table_name='oeerecord')
    op.drop_table('oeerecord')
    # ### end Alembic commands ###
