"""Initial tables

Revision ID: 85a71ab74cdc
Revises: 
Create Date: 2026-06-28 09:00:36.663560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a71ab74cdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_id'), 'machine', ['id'], unique=False)
    op.create_index(op.f('ix_machine_name'), 'machine', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('telemetry',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('vibration_x', sa.Float(), nullable=True),
    sa.Column('vibration_y', sa.Float(), nullable=True),
    sa.Column('vibration_z', sa.Float(), nullable=True),
    sa.Column('temperature_spindle', sa.Float(), nullable=True),
    sa.Column('temperature_coolant', sa.Float(), nullable=True),
    sa.Column('current_l1', sa.Float(), nullable=True),
    sa.Column('current_l2', sa.Float(), nullable=True),
    sa.Column('current_l3', sa.Float(), nullable=True),
    sa.Column('pressure_coolant', sa.Float(), nullable=True),
    sa.Column('pressure_air', sa.Float(), nullable=True),
    sa.Column('rpm_spindle', sa.Float(), nullable=True),
    sa.Column('cutting_force', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('time', 'machine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_machine_name'), table_name='machine')
    op.drop_index(op.f('ix_machine_id'), table_name='machine')
    op.drop_table('machine')
    # ### end Alembic commands ###
